config/routes.rb
Rails.application.routes.draw do
  resources :returneds
  resources :waitlists
  resources :renteds
  resources :tapes
  resources :clients
  resources :actors
  resources :directors
  resources :genres
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :client_genres, :dependent => :destroy
    has_many :client_directors, :dependent => :destroy
    has_many :client_actors, :dependent => :destroy
    has_many :genres, through: :client_genres
    has_many :directors, through: :client_directors
    has_many :actors, through: :client_actors
    has_many :renteds

    before_create :generate_code

    def generate_code
       self.code = SecureRandom.hex(10)
    end
end

app/models/client_actor.rb
class ClientActor < ApplicationRecord
  belongs_to :client
  belongs_to :actor
end

app/models/client_director.rb
class ClientDirector < ApplicationRecord
  belongs_to :client
  belongs_to :director
end

app/models/client_genre.rb
class ClientGenre < ApplicationRecord
  belongs_to :client
  belongs_to :genre
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :tapes
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :clients
end

app/models/rented.rb
class Rented < ApplicationRecord
  belongs_to :tape
  belongs_to :client
  after_create :handle_rent

  def handle_rent
    tape = Tape.find(self.tape_id)
    tape.available = false
    tape.save()
  end
  
end

app/models/returned.rb
class Returned < ApplicationRecord
  belongs_to :tape
  belongs_to :client
  after_create :handle_return
  after_create :notify

  def handle_return
    tape = Tape.find(self.tape_id)
    tape.available = true
    tape.save()
  end

  def notify
    @waitlist = Waitlist.where(tape_id: self.tape_id).first
    if @waitlist
      WaitlistMailer.with(client: @waitlist.client, tape: @waitlist.tape).notify.deliver_now
    end
    @waitlist.destroy
  end
end

app/models/tape.rb
class Tape < ApplicationRecord
  has_many :tape_genres, :dependent => :destroy
  has_many :tape_actors, :dependent => :destroy
  belongs_to :director
  has_many :actors, through: :tape_actors
  has_many :genres, through: :tape_genres

  before_create :generate_code

  def generate_code
      self.code = SecureRandom.hex(10)
  end
end

app/models/tape_actor.rb
class TapeActor < ApplicationRecord
  belongs_to :tape
  belongs_to :actor
end

app/models/tape_genre.rb
class TapeGenre < ApplicationRecord
  belongs_to :tape
  belongs_to :genre
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
  belongs_to :tape
  belongs_to :client
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  before_action :set_tape, only: [:show, :edit, :update, :destroy]

  # GET /tapes
  # GET /tapes.json
  def index
    @tapes = Tape.all
  end

  # GET /tapes/1
  # GET /tapes/1.json
  def show
  end

  # GET /tapes/new
  def new
    @tape = Tape.new
  end

  # GET /tapes/1/edit
  def edit
  end

  # POST /tapes
  # POST /tapes.json
  def create
    @tape = Tape.new(tape_params)

    respond_to do |format|
      if @tape.save
        format.html { redirect_to @tape, notice: 'Tape was successfully created.' }
        format.json { render :show, status: :created, location: @tape }
      else
        format.html { render :new }
        format.json { render json: @tape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tapes/1
  # PATCH/PUT /tapes/1.json
  def update
    respond_to do |format|
      if @tape.update(tape_params)
        format.html { redirect_to @tape, notice: 'Tape was successfully updated.' }
        format.json { render :show, status: :ok, location: @tape }
      else
        format.html { render :edit }
        format.json { render json: @tape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tapes/1
  # DELETE /tapes/1.json
  def destroy
    @tape.destroy
    respond_to do |format|
      format.html { redirect_to tapes_url, notice: 'Tape was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tape
      @tape = Tape.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tape_params
      params.require(:tape).permit(:name, :code, :director_id, genre_ids: [], actor_ids: [])
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/renteds_helper.rb
module RentedsHelper
end

app/helpers/returneds_helper.rb
module ReturnedsHelper
end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/tapes/_form.html.erb
<%= semantic_form_for @tape do |f| %>
    <%= f.inputs do %>
      <%= f.input :name %>
      <%= f.input :director, :as => :select %>
      <%= f.input :genres, :as => :select, :multiple => true %>
      <%= f.input :actors, :as => :select, :input_html => { :multiple => true } %>
    <% end %>
    <%= f.actions do %>
      <%= f.action :submit, :as => :button %>
      <%= f.action :cancel, :as => :link %>
    <% end %>
  <% end %>

app/views/tapes/edit.html.erb
<h1>Editing Tape</h1>

<%= render 'form', tape: @tape %>

<%= link_to 'Ver', @tape %> |
<%= link_to 'Back', tapes_path %>

app/views/tapes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peliculas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Codigo</th>
      <th>Director</th>
      <th>Disponible?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tapes.each do |tape| %>
      <tr>
        <td><%= tape.name %></td>
        <td><%= tape.code %></td>
        <td><%= tape.director.name %></td>
        <td><%= tape.available %></td>
        <td><%= link_to 'Ver', tape %></td>
        <td><%= link_to 'Editar', edit_tape_path(tape) %></td>
        <td><%= link_to 'Borrar', tape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tape', new_tape_path %>

app/views/tapes/new.html.erb
<h1>New Tape</h1>

<%= render 'form', tape: @tape %>

<%= link_to 'Back', tapes_path %>

app/views/tapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tape.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @tape.code %>
</p>

<p>
  <strong>Director:</strong>
  <%= @tape.director.name %>
</p>

<strong>Genres:</strong>
<ul>
<% @tape.genres.each do |genre| %>
  <li> <%= genre.name %> </li>
<% end %>
</ul>

<strong>Actors:</strong>
<ul>
<% @tape.actors.each do |actor| %>
  <li> <%= actor.name %> </li>
<% end %>
</ul>

<%= link_to 'Editar', edit_tape_path(@tape) %> |
<%= link_to 'Back', tapes_path %>