config/routes.rb
Rails.application.routes.draw do
  resources :returneds
  resources :waitlists
  resources :renteds
  resources :tapes
  resources :clients
  resources :actors
  resources :directors
  resources :genres
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :client_genres, :dependent => :destroy
    has_many :client_directors, :dependent => :destroy
    has_many :client_actors, :dependent => :destroy
    has_many :genres, through: :client_genres
    has_many :directors, through: :client_directors
    has_many :actors, through: :client_actors
    has_many :renteds

    before_create :generate_code

    def generate_code
       self.code = SecureRandom.hex(10)
    end
end

app/models/client_actor.rb
class ClientActor < ApplicationRecord
  belongs_to :client
  belongs_to :actor
end

app/models/client_director.rb
class ClientDirector < ApplicationRecord
  belongs_to :client
  belongs_to :director
end

app/models/client_genre.rb
class ClientGenre < ApplicationRecord
  belongs_to :client
  belongs_to :genre
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :tapes
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :clients
end

app/models/rented.rb
class Rented < ApplicationRecord
  belongs_to :tape
  belongs_to :client
  after_create :handle_rent

  def handle_rent
    tape = Tape.find(self.tape_id)
    tape.available = false
    tape.save()
  end
  
end

app/models/returned.rb
class Returned < ApplicationRecord
  belongs_to :tape
  belongs_to :client
  after_create :handle_return
  after_create :notify

  def handle_return
    tape = Tape.find(self.tape_id)
    tape.available = true
    tape.save()
  end

  def notify
    @waitlist = Waitlist.where(tape_id: self.tape_id).first
    if @waitlist
      WaitlistMailer.with(client: @waitlist.client, tape: @waitlist.tape).notify.deliver_now
    end
    @waitlist.destroy
  end
end

app/models/tape.rb
class Tape < ApplicationRecord
  has_many :tape_genres, :dependent => :destroy
  has_many :tape_actors, :dependent => :destroy
  belongs_to :director
  has_many :actors, through: :tape_actors
  has_many :genres, through: :tape_genres

  before_create :generate_code

  def generate_code
      self.code = SecureRandom.hex(10)
  end
end

app/models/tape_actor.rb
class TapeActor < ApplicationRecord
  belongs_to :tape
  belongs_to :actor
end

app/models/tape_genre.rb
class TapeGenre < ApplicationRecord
  belongs_to :tape
  belongs_to :genre
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
  belongs_to :tape
  belongs_to :client
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actor_params
      params.require(:actor).permit(:name)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/renteds_helper.rb
module RentedsHelper
end

app/helpers/returneds_helper.rb
module ReturnedsHelper
end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/actors/_form.html.erb
<%= form_with(model: actor, local: true) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
        <% actor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Ver', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actores</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= link_to 'Ver', actor %></td>
        <td><%= link_to 'Editar', edit_actor_path(actor) %></td>
        <td><%= link_to 'Borrar', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva entrada', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<%= link_to 'Editar', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>