config/routes.rb
Rails.application.routes.draw do
  resources :returneds
  resources :waitlists
  resources :renteds
  resources :tapes
  resources :clients
  resources :actors
  resources :directors
  resources :genres
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :client_genres, :dependent => :destroy
    has_many :client_directors, :dependent => :destroy
    has_many :client_actors, :dependent => :destroy
    has_many :genres, through: :client_genres
    has_many :directors, through: :client_directors
    has_many :actors, through: :client_actors
    has_many :renteds

    before_create :generate_code

    def generate_code
       self.code = SecureRandom.hex(10)
    end
end

app/models/client_actor.rb
class ClientActor < ApplicationRecord
  belongs_to :client
  belongs_to :actor
end

app/models/client_director.rb
class ClientDirector < ApplicationRecord
  belongs_to :client
  belongs_to :director
end

app/models/client_genre.rb
class ClientGenre < ApplicationRecord
  belongs_to :client
  belongs_to :genre
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :tapes
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :clients
end

app/models/rented.rb
class Rented < ApplicationRecord
  belongs_to :tape
  belongs_to :client
  after_create :handle_rent

  def handle_rent
    tape = Tape.find(self.tape_id)
    tape.available = false
    tape.save()
  end
  
end

app/models/returned.rb
class Returned < ApplicationRecord
  belongs_to :tape
  belongs_to :client
  after_create :handle_return
  after_create :notify

  def handle_return
    tape = Tape.find(self.tape_id)
    tape.available = true
    tape.save()
  end

  def notify
    @waitlist = Waitlist.where(tape_id: self.tape_id).first
    if @waitlist
      WaitlistMailer.with(client: @waitlist.client, tape: @waitlist.tape).notify.deliver_now
    end
    @waitlist.destroy
  end
end

app/models/tape.rb
class Tape < ApplicationRecord
  has_many :tape_genres, :dependent => :destroy
  has_many :tape_actors, :dependent => :destroy
  belongs_to :director
  has_many :actors, through: :tape_actors
  has_many :genres, through: :tape_genres

  before_create :generate_code

  def generate_code
      self.code = SecureRandom.hex(10)
  end
end

app/models/tape_actor.rb
class TapeActor < ApplicationRecord
  belongs_to :tape
  belongs_to :actor
end

app/models/tape_genre.rb
class TapeGenre < ApplicationRecord
  belongs_to :tape
  belongs_to :genre
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
  belongs_to :tape
  belongs_to :client
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:code, :email, :name, :address, :phone, genre_ids: [], director_ids: [], actor_ids: [])
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/renteds_helper.rb
module RentedsHelper
end

app/helpers/returneds_helper.rb
module ReturnedsHelper
end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/clients/_form.html.erb
<%= semantic_form_for @client do |f| %>
    <%= f.inputs do %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :address %>
      <%= f.input :phone %>
      <%= f.input :genres, :as => :select, :multiple => true %>
      <%= f.input :directors, :as => :select, :input_html => { :multiple => true } %>
      <%= f.input :actors, :as => :select, :input_html => { :multiple => true } %>
    <% end %>
    <%= f.actions do %>
      <%= f.action :submit, :as => :button %>
      <%= f.action :cancel, :as => :link %>
    <% end %>
  <% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Ver', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.code %></td>
        <td><%= client.name %></td>
        <td><%= client.email %></td>
        <td><%= client.address %></td>
        <td><%= client.phone %></td>
        <td><%= link_to 'Ver', client %></td>
        <td><%= link_to 'Editar', edit_client_path(client) %></td>
        <td><%= link_to 'Borrar', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva entrada', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @client.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>


<strong>Genres:</strong>
<ul>
<% @client.genres.each do |genre| %>
  <li> <%= genre.name %> </li>
<% end %>
</ul>

<strong>Directors:</strong>
<ul>
<% @client.directors.each do |director| %>
  <li> <%= director.name %> </li>
<% end %>
</ul>

<strong>Actors:</strong>
<ul>
<% @client.actors.each do |actor| %>
  <li> <%= actor.name %> </li>
<% end %>
</ul>

<%= link_to 'Editar', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>